
 Loading and Processing Data...
Traceback (most recent call last):
  File "/home/ball4537/anaconda3/envs/dirvrnn-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ball4537/anaconda3/envs/dirvrnn-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/dirvrnn_run.py", line 126, in <module>
    main()
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/dirvrnn_run.py", line 63, in main
    data_dic = loader.prepare_input(seed=seed, train_val_ratio=train_val_ratio, train_ratio=train_ratio, shuffle=True, K_folds=K_folds)
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/data_processing/DataLoader.py", line 543, in prepare_input
    y,
NameError: name 'y' is not defined